language: node_js
sudo: false
node_js:
  - "4.2.3"
  - "5.2.0"
# NodeJS v4 requires gcc 4.8
env:
  - NODE_ENV=travis CXX="g++-4.8" CC="gcc-4.8"
matrix:
  allow_failures:
    - node_js: 5
services:
  - mongodb
# gcc 4.8 requires ubuntu-toolchain-r-test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
    - clang
before_install:
  - npm install -g npm
  - npm install -g gulp
  - npm install
before_script:
script:
after_script:
  - gulp test